configs:
  ix-update-hosts-script.sh:
    content: >-
      #!/bin/bash

      config_file="/var/www/html/config/config.php"


      echo "Updating database and redis host in config.php"

      sed -i "s/\('dbhost' => '\)[^']*postgres:5432',/\1postgres:5432',/"
      "$$config_file" || { echo "Failed to update database host. Exiting...";
      exit 1; }

      occ config:system:set redis host --value="redis" || { echo "Failed to
      update redis host. Continuing..."; exit 0; }
  ix-update-trusted-domains-script.sh:
    content: >-
      #!/bin/bash

      set_list() {
        list_name="$${1:?"list_name is unset"}"
        space_delimited_values="$${2:?"space_delimited_values is unset"}"

        # Get current list
        current_list="$$(occ config:system:get "$$list_name")"
        # Convert newline separated values to space separated
        current_list="$$(echo "$$current_list" | tr '\n' ' ')"
        # Merge current list with new values
        merged_list="$$(echo "$$current_list $$space_delimited_values" | tr ' ' '\n' | xargs -I{} echo {})"
        # Remove duplicate values
        merged_list="$$(echo "$$merged_list" | tr ' ' '\n' | sort -u | tr '\n' ' ')"

        if [ -n "$${merged_list}" ]; then
          # Remove current list, so we can replace it with the new one
          occ config:system:delete "$$list_name" || return

          IDX=0
          # Replace spaces with newlines so the input can have
          # mixed entries of space or new line separated values
          echo "$$merged_list" | tr ' ' '\n' | while IFS= read -r value; do
              # Skip empty values
              if [ -z "$$value" ]; then
                continue
              fi

              occ config:system:set "$$list_name" $$IDX --value="$$value"

              IDX=$$((IDX+1))
          done
        fi
      }


      echo "Updating trusted domains. It will append new domains to the existing
      list."

      echo "If you see a domain that is not longer valid, you need to manually
      remove it from the list in the config.php file."


      set_list "trusted_domains" "$${NEXTCLOUD_TRUSTED_DOMAINS}" || { echo
      "Failed to update trusted domains. Continuing..."; exit 0; }
  limitrequestbody.conf:
    content: LimitRequestBody 3221225472
  occ:
    content: |-
      #!/bin/bash
      uid="$$(id -u)"
      gid="$$(id -g)"
      if [ "$$uid" = "0" ]; then
        user='www-data'
        group='www-data'
      else
        user="$$uid"
        group="$$gid"
      fi
      run_as() {
        if [ "$$(id -u)" = "0" ]; then
          su -p "$$user" -s /bin/bash -c "php /var/www/html/occ $$(printf '%q ' "$$@")"
        else
          /bin/bash -c "php /var/www/html/occ $$(printf '%q ' "$$@")"
        fi
      }
      run_as "$$@"
  opcache.ini:
    content: opcache.memory_consumption=128
  permissions_actions_data:
    content: >-
      [{"mount_path": "/mnt/permission/postgres_postgres_data", "is_temporary":
      false, "identifier": "postgres_postgres_data", "recursive": false, "mode":
      "check", "uid": 999, "gid": 999, "chmod": null}, {"mount_path":
      "/mnt/permission/redis_redis_data", "is_temporary": true, "identifier":
      "redis_redis_data", "recursive": true, "mode": "check", "uid": 1001,
      "gid": 0, "chmod": null}]
  permissions_run_script:
    content: |
      #!/usr/bin/env python3

      import os
      import json
      import time
      import shutil

      with open("/script/actions.json", "r") as f:
          actions_data = json.load(f)

      if not actions_data:
          # If this script is called, there should be actions data
          raise ValueError("No actions data found")

      def fix_perms(path, chmod, recursive=False):
          print(f"Changing permissions{' recursively ' if recursive else ' '}to {chmod} on: [{path}]")
          os.chmod(path, int(chmod, 8))
          if recursive:
              for root, dirs, files in os.walk(path):
                  for f in files:
                      os.chmod(os.path.join(root, f), int(chmod, 8))
          print("Permissions after changes:")
          print_chmod_stat()

      def fix_owner(path, uid, gid, recursive=False):
          print(f"Changing ownership{' recursively ' if recursive else ' '}to {uid}:{gid} on: [{path}]")
          os.chown(path, uid, gid)
          if recursive:
              for root, dirs, files in os.walk(path):
                  for f in files:
                      os.chown(os.path.join(root, f), uid, gid)
          print("Ownership after changes:")
          print_chown_stat()

      def print_chown_stat():
          curr_stat = os.stat(action["mount_path"])
          print(f"Ownership: [{curr_stat.st_uid}:{curr_stat.st_gid}]")

      def print_chmod_stat():
          curr_stat = os.stat(action["mount_path"])
          print(f"Permissions: [{oct(curr_stat.st_mode)[3:]}]")

      def print_chown_diff(curr_stat, uid, gid):
          print(f"Ownership: wanted [{uid}:{gid}], got [{curr_stat.st_uid}:{curr_stat.st_gid}].")

      def print_chmod_diff(curr_stat, mode):
          print(f"Permissions: wanted [{mode}], got [{oct(curr_stat.st_mode)[3:]}].")

      def perform_action(action):
          start_time = time.time()
          print(f"=== Applying configuration on volume with identifier [{action['identifier']}] ===")

          if not os.path.isdir(action["mount_path"]):
              print(f"Path [{action['mount_path']}] is not a directory, skipping...")
              return

          if action["is_temporary"]:
              print(f"Path [{action['mount_path']}] is a temporary directory, ensuring it is empty...")
              for item in os.listdir(action["mount_path"]):
                  item_path = os.path.join(action["mount_path"], item)

                  # Exclude the safe directory, where we can use to mount files temporarily
                  if os.path.basename(item_path) == "ix-safe":
                      continue
                  if os.path.isdir(item_path):
                      shutil.rmtree(item_path)
                  else:
                      os.remove(item_path)

          if not action["is_temporary"] and os.listdir(action["mount_path"]):
              print(f"Path [{action['mount_path']}] is not empty, skipping...")
              return

          print(f"Current Ownership and Permissions on [{action['mount_path']}]:")
          curr_stat = os.stat(action["mount_path"])
          print_chown_diff(curr_stat, action["uid"], action["gid"])
          print_chmod_diff(curr_stat, action["chmod"])
          print("---")

          if action["mode"] == "always":
              fix_owner(action["mount_path"], action["uid"], action["gid"], action["recursive"])
              if not action["chmod"]:
                  print("Skipping permissions check, chmod is falsy")
              else:
                  fix_perms(action["mount_path"], action["chmod"], action["recursive"])
              return

          elif action["mode"] == "check":
              if curr_stat.st_uid != action["uid"] or curr_stat.st_gid != action["gid"]:
                  print("Ownership is incorrect. Fixing...")
                  fix_owner(action["mount_path"], action["uid"], action["gid"], action["recursive"])
              else:
                  print("Ownership is correct. Skipping...")

              if not action["chmod"]:
                  print("Skipping permissions check, chmod is falsy")
              else:
                  if oct(curr_stat.st_mode)[3:] != action["chmod"]:
                      print("Permissions are incorrect. Fixing...")
                      fix_perms(action["mount_path"], action["chmod"], action["recursive"])
                  else:
                      print("Permissions are correct. Skipping...")

          print(f"Time taken: {(time.time() - start_time) * 1000:.2f}ms")
          print(f"=== Finished applying configuration on volume with identifier [{action['identifier']}] ==")
          print()

      if __name__ == "__main__":
          start_time = time.time()
          for action in actions_data:
              perform_action(action)
          print(f"Total time taken: {(time.time() - start_time) * 1000:.2f}ms")
  php.ini:
    content: max_execution_time=30
services:
  nextcloud:
    build:
      dockerfile_inline: |
        FROM nextcloud:31.0.5
      tags:
        - >-
          ix-nextcloud:31.0.5_8f2b4bb943e1f97a1880f139d5500688714cabeb8f1d4a5c5e6e88013ca830c9
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - NET_RAW
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    configs:
      - mode: 493
        source: ix-update-hosts-script.sh
        target: /docker-entrypoint-hooks.d/before-starting/ix-update-hosts-script.sh
      - mode: 493
        source: ix-update-trusted-domains-script.sh
        target: >-
          /docker-entrypoint-hooks.d/before-starting/ix-update-trusted-domains-script.sh
      - source: limitrequestbody.conf
        target: /etc/apache2/conf-enabled/limitrequestbody.conf
      - mode: 493
        source: occ
        target: /usr/local/bin/occ
      - source: opcache.ini
        target: /usr/local/etc/php/conf.d/opcache-z-99.ini
      - source: php.ini
        target: /usr/local/etc/php/conf.d/nextcloud-z-99.ini
    depends_on:
      permissions:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    environment:
      NEXTCLOUD_ADMIN_PASSWORD: a7374977
      NEXTCLOUD_ADMIN_USER: awei801122
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_TRUSTED_DOMAINS: '["127.0.0.1", "localhost", "nextcloud", "nas.yuntech.idv.tw", "192.168.1.150"]'
      OVERWRITEPROTOCOL: http
      OVERWRITECLIURL: http://192.168.1.150:30027
      NVIDIA_VISIBLE_DEVICES: void
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_LIMIT: 20G
      PHP_POST_MAX_SIZE: 20G 
      POSTGRES_DB: nextcloud
      POSTGRES_HOST: postgres:5432
      POSTGRES_PASSWORD: a7374977
      POSTGRES_USER: nextcloud
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: a7374977
      REDIS_HOST_PORT: '6379'
      TZ: Etc/UTC
      UMASK: '002'
      UMASK_SET: '002'
    group_add:
      - 568
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: >-
        curl --silent --output /dev/null --show-error --fail --header "Host:
        localhost" http://127.0.0.1:80/status.php
      timeout: 5s
    image: >-
      ix-nextcloud:31.0.5_8f2b4bb943e1f97a1880f139d5500688714cabeb8f1d4a5c5e6e88013ca830c9
    platform: linux/amd64
    ports:
      - mode: ingress
        protocol: tcp
        published: 30027
        target: 80
    privileged: False
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    stdin_open: False
    tty: False
    user: '0:0'
    volumes:
      - read_only: False
        target: /tmp
        type: volume
        volume:
          nocopy: False
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/.ix-apps/app_mounts/nextcloud/html
        target: /var/www/html
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/.ix-apps/app_mounts/nextcloud/data
        target: /var/www/html/data
        type: bind
  permissions:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    cap_drop:
      - ALL
    configs:
      - mode: 320
        source: permissions_actions_data
        target: /script/actions.json
      - mode: 448
        source: permissions_run_script
        target: /script/run.py
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    entrypoint:
      - python3
      - /script/run.py
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TZ: Etc/UTC
      UMASK: '002'
      UMASK_SET: '002'
    group_add:
      - 568
    healthcheck:
      disable: True
    image: python:3.13.0-slim-bookworm
    network_mode: none
    platform: linux/amd64
    privileged: False
    restart: on-failure:1
    security_opt:
      - no-new-privileges=true
    stdin_open: False
    tty: False
    user: '0:0'
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/.ix-apps/app_mounts/nextcloud/postgres_data
        target: /mnt/permission/postgres_postgres_data
        type: bind
      - read_only: False
        source: redis-data
        target: /mnt/permission/redis_redis_data
        type: volume
        volume:
          nocopy: False
  postgres:
    cap_drop:
      - ALL
    depends_on:
      permissions:
        condition: service_completed_successfully
      postgres_upgrade:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: a7374977
      POSTGRES_PORT: '5432'
      POSTGRES_USER: nextcloud
      TZ: Etc/UTC
      UMASK: '002'
      UMASK_SET: '002'
    group_add:
      - 568
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: pg_isready -h 127.0.0.1 -p 5432 -U $$POSTGRES_USER -d $$POSTGRES_DB
      timeout: 5s
    image: postgres:13.21
    platform: linux/amd64
    privileged: False
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    stdin_open: False
    tty: False
    user: '999:999'
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/.ix-apps/app_mounts/nextcloud/postgres_data
        target: /var/lib/postgresql/data
        type: bind
  postgres_upgrade:
    cap_drop:
      - ALL
    depends_on:
      permissions:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    entrypoint:
      - /bin/bash
      - '-c'
      - /upgrade.sh
    environment:
      DATA_DIR: /var/lib/postgresql/data
      NVIDIA_VISIBLE_DEVICES: void
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: a7374977
      POSTGRES_PORT: '5432'
      POSTGRES_USER: nextcloud
      TARGET_VERSION: '13'
      TZ: Etc/UTC
      UMASK: '002'
      UMASK_SET: '002'
    group_add:
      - 568
    healthcheck:
      disable: True
    image: ixsystems/postgres-upgrade:1.0.2
    platform: linux/amd64
    privileged: False
    restart: on-failure:1
    security_opt:
      - no-new-privileges=true
    stdin_open: False
    tty: False
    user: '999:999'
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/.ix-apps/app_mounts/nextcloud/postgres_data
        target: /var/lib/postgresql/data
        type: bind
  redis:
    cap_drop:
      - ALL
    depends_on:
      permissions:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      NVIDIA_VISIBLE_DEVICES: void
      REDIS_PASSWORD: a7374977
      REDIS_PORT_NUMBER: '6379'
      TZ: Etc/UTC
      UMASK: '002'
      UMASK_SET: '002'
    group_add:
      - 568
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: redis-cli -h 127.0.0.1 -p 6379 -a $$REDIS_PASSWORD ping | grep -q PONG
      timeout: 5s
    image: bitnami/redis:8.0.1
    platform: linux/amd64
    privileged: False
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    stdin_open: False
    tty: False
    user: '1001:0'
    volumes:
      - read_only: False
        source: redis-data
        target: /bitnami/redis/data
        type: volume
        volume:
          nocopy: False
volumes:
  redis-data: {}
x-notes: >+
  # Nextcloud


  ## Bug Reports and Feature Requests


  If you find a bug in this app or have an idea for a new feature, please file
  an issue at

  https://github.com/truenas/apps

x-portals:
  - host: 0.0.0.0
    name: Web UI
    path: /
    port: 30027
    scheme: http
